name: upper-cross

on:
  push:
    paths:
      - ".github/workflows/upper-cross.yml"
      - "upper/**"
  workflow_dispatch: # manual

jobs:
  cross:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: upper
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22
          cache-dependency-path: ./upper/go.sum
      - run: ./build.xplat.sh
      - uses: actions/upload-artifact@v4
        with:
          path: ./upper/bin/upper*
          name: build
